# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_auto_20161020_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
